### PR TITLE
Typo in the network name

### PR DESCRIPTION
**Pull request by sergun4ik**
The previous container created (myhero_data) actually creates a bridge called myherodata_default, not myhero_data_default

### CODE REVIEW

**Comment by juliogomez** [comment]
hmmm, I get the right network when running `docker-compose up` in myhero-data:

```
docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
fd95ee130981        bridge                bridge              local
19c90501507d        host                  host                local
6b18b2ed6e93        myhero_data_default   bridge              local
5c62a19d578b        none                  null                local
```

**Comment by sergun4ik** [comment]
That's strange. I've got a Mint VM running in Virtualbox. Just removed and cloned the myhero_data again and it still creates this network
```
sergey@mint1:~/myhero_data$ sudo docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
7d5d3d770ebd        br01                 bridge              local
250defbcb065        bridge               bridge              local
60969f6aef20        host                 host                local
a0bf73b3ad16        myherodata_default   bridge              local
38b4d313fc1b        none                 null                local
sergey@mint1:~/myhero_data$ 
```

My docker version is 
Docker version 18.09.7, build 2d0083d

**Comment by juliogomez** [comment]
not sure why this might be happening, I got docker running natively in my mac:

```
docker --version
Docker version 19.03.5, build 633a0ea
```

**Comment by sergun4ik** [comment]
Updated the docker to 19.03.06.
```
still the same
sergey@mint1:~/myhero_data$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
sergey@mint1:~/myhero_data$ sudo docker network ls
[sudo] password for sergey:         
NETWORK ID          NAME                 DRIVER              SCOPE
7d5d3d770ebd        br01                 bridge              local
2b217d188a9e        bridge               bridge              local
60969f6aef20        host                 host                local
a0bf73b3ad16        myherodata_default   bridge              local
38b4d313fc1b        none                 null                local
sergey@mint1:~/myhero_data$ docker --version
Docker version 19.03.6, build 369ce74a3c
sergey@mint1:~/myhero_data$
```

The actual network name isn't specified in any of the setup files, right?

**Comment by juliogomez** [comment]
maybe it is an arch thing, could you try natively in your laptop?

**Comment by sergun4ik** [comment]
Looks like it is version/OS specific. I have tried it on my Windows 10 laptop with Docker 19.03.5 and it works correctly. :)

**Comment by juliogomez** [comment]
ahh, I see, great finding anyways!

**Pull request closed without merging**
